[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Copyright (c) 2024-present The ScrapComputers Team'
    alertText = 'This is a development build! The documentation may be incomplete or unfinished and anything can change!'
